apiVersion: v1
kind: Pod
metadata:
  name: guestbook-container
  labels:
    visualize: "true"
spec:
  containers:
  - name: php-redis
    image: gcr.io/google_samples/gb-frontend:v3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    env:
    - name: GET_HOSTS_FROM
      value: dns
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-container
  labels:
    app: guestbook
    tier: frontend
    visualize: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
