apiVersion: v1
kind: Pod
metadata:
  name: redis-slave-container
  labels:
    visualize: "true"
spec:
  containers:
    - name: slave
      image: gcr.io/google_samples/gb-redisslave:v1
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave-container
  labels:
    app: redis
    role: slave
    tier: backend
    visualize: "true"
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend
